[package]
name = "shieldedpay-claim"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
shieldedpay-payroll = { path = "../payroll" }
shieldedpay-treasury = { path = "../treasury" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
